In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3],dtype = 'int16')
print (a)

[1 2 3]


In [3]:
b = np.array([[5.0,6.0,7.0],[32.0,43.0,32.0]])
print(b)

[[ 5.  6.  7.]
 [32. 43. 32.]]


In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
a.dtype

dtype('int16')

In [9]:
b.dtype

dtype('float64')

In [10]:
a.itemsize # tells in bytes

2

In [11]:
b.itemsize

8

In [12]:
a.nbytes

6

In [13]:
b.nbytes

48

In [14]:
#FOR A SPECIFIC COLUMN
print(b[1,:])

[32. 43. 32.]


In [15]:
#FOR A SPECIFIC row
print(b[:,1])

[ 6. 43.]
